### ISSUE TITLE
[1.01 ] XP Multiplication Bugs  ( And even extremer if Clumps is installed )

### ISSUE THREAD

**Issue by Cakx** [Insane-96/XpHolder#4] opened 2018-08-10 02:27 UTC
**The XP Holder can easily be abused to generate more XP out of nothing.**

1. (With just this mod installed)
When you input your full amount of xp (letzs say something like  ~2.33) and then start withdrawing and depositing with 100% amount again and again for some time. The amount of  xp grows leading to something like 3,4 when the behaviour suddenly stops.  This is just one example.

2. (With just this mod installed)
When you input all your XP, then withdraw all, then start inputting small amounts of xp (10,3% or so) you can continually click the deposit button and increase your XP as long as you want. The player never runs out of XP and the Holders storage grows further and further. That was another example.

Maybe it's some rounding errors? I haven't looked at your code yet.

3. (With "Clumps" installed)
When "Clumps" (a popular lag reducing mod that affects xp orbs) is installed the problem gets even worse as breaking a xp holder that has some xp in it drops a lot more xp than the stored amount. By refilling and redoing this process  you can generate infinite amounts xp very fast. But I can't say if this problem comes from clumps or from your mod.

All in all there are to many ways to abuse this machine right now. Tested with latest as well as with the recomended forge version.
I hope you can fix these issues as the concept is done very very nice. :)

**Comment by Insane96** [comment] 2018-08-25 07:26
1. Managed to reproduce this. Seems like to happen more likely with low levels.
2. Managed to reprocude this too with low levels. Seems to be a rounding problem.
3. The XP drops correctly when the mod isn't installed so I don't know why this happens.

**Comment by Insane96** [comment] 2018-12-28 08:54
This has been fixed in 2.0 since the mod got a rewrite and it's simpler in general

**Closed as completed by Insane96** 2018-12-28 08:54 UTC
Labels: bug
